#%RAML 0.8
title: Plashboard
version: v1
baseUri: http://localhost/
#baseUri: http://localhost/api/{version}
mediaType: application/json

schemas:
  - measures: schema/plashboard-measures.json
    userCommands: schema/plashboard-userCommands.json
    message: schema/plashboard-message.json
    authentication: schema/plashboard-authentication.json
    authorized: schema/plashboard-authorized.json
    hardwareConfiguration: schema/plashboard-hardwareConfiguration.json

traits:
  - secured:
        usage: Apply this to any method that needs to be secured
        description: Some requests require authentication
        headers:
            Authorization:
                description: |
                    The user have to require an authentification session provided by /authorize method.
                required: true
        responses:
            401:
                body:
                    application/json:
                        schema: message
                        example: |
                            {
                                "code": 401,
                                "message": "Authorized require"
                            }
    basic:
        usage: Apply this to any method that needs basic methods
        description: Some requests require basics messages
        responses:
            404:
                body:
                    application/json:
                        schema: message
                        example: |
                            {
                                "code": 404,
                                "message": "Not found"
                            }
            405:
                body:
                    application/json:
                        schema: message
                        example: |
                            {
                                "code": 405,
                                "message": "Methode POST not allowed"
                            }

    timeSearchable:
        usage: Apply this to any method that can be filter by timestamp
        description: Some requests can search data with time filter
        queryParameters:
            time:
                description: Date time to start the search
                example: "2015-03-04 15:00:00"
                required: false
                type: string

    limitedSearchable:
        usage: Apply this to any method that can be respond a number max of result
        description: Some requests can search data with max result to given back
        queryParameters:
            xlast:
                description: Number of result max to given back
                example: 5
                required: false
                type: integer

/authorize:
    post:
        description: |
            Authentificate user to access data
        queryParameters:
            user:
                description: Name for the user account
                required: true
                type: string
            password:
                description: Hashed sha password for the user account
                example: "MissPepper01091963 give 89018eab1dcab8bba137b1b13b54e079a924cd7c"
                required: true
                type: string
        body:
            application/json:
                schema: authentication
                example: |
                    {
                        "username": "Stark",
                        "password": "89018eab1dcab8bba137b1b13b54e079a924cd7c"
                    }
        responses:
            200:
                body:
                    application/json:
                        schema: message
                        example: |
                            {
                                "code": 200,
                                "message": "You are now logged"
                            }
            401:
                body:
                    application/json:
                        schema: message
                        example: |
                            {
                                "code": -1,
                                "message": "Username and password invalid"
                            }
            400:
                body:
                    application/json:
                        schema: message
                        example: |
                            {
                                "code": 400,
                                "message": "Bad parameters"
                            }
            405:
                body:
                    application/json:
                        schema: message
                        example: |
                            {
                                "code": 405,
                                "message": "Methode GET not allowed"
                            }
            500:
                body:
                    application/json:
                        schema: message
                        example: |
                            {
                                "code": 500,
                                "message": "Something went wrong in the server"
                            }
    delete:
        description: |
            Delete the authentification
        responses:
            200:
                body:
                    application/json:
                        schema: message
                        example: |
                            {
                                "code": 200,
                                "message": "You are disconnected"
                            }
            400:
                body:
                    application/json:
                        schema: message
                        example: |
                            {
                                "code": 400,
                                "message": "You are already disconnected"
                            }

/measures:
    get:
        is: [ basic, secured, timeSearchable, limitedSearchable ]
        description: Get all measures for sensors.
        responses:
            200:
                body:
                    application/json:
                        schema: measures
                        example: |
                            [
                                {
                                    "id": 1,
                                    "hardwareConfigurationId": 5,
                                    "hardwareName": "temperature_sensor",
                                    "value": 21,
                                    "timestamp": "2015-03-03 14:22:00"
                                },
                                {
                                    "id": 2,
                                    "hardwareConfigurationId": 6,
                                    "hardwareName": "ph_sensor",
                                    "value": 7,
                                    "timestamp": "2015-03-03 14:35:03"
                                },
                                {
                                    "id": 3,
                                    "hardwareConfigurationId": 9,
                                    "hardwareName": "pressure_sensor",
                                    "value": 4,
                                    "timestamp": "2015-03-03 14:40:52"
                                }	
                            ]
    /{sensorId}:
        description: Get measure for a specific sensor.
        get:
            is: [ basic, secured, timeSearchable, limitedSearchable ]
            description: Get the measure with `hardwareConfigurationId = {sensorId}`.
            responses:
                200:
                    body:
                        application/json:
                            schema: measures
                            example: |
                                {
                                    "id": 1,
                                    "hardwareConfigurationId": 5,
                                    "hardwareName": "temperature_sensor",
                                    "value": 21,
                                    "timestamp": "2015-03-03 14:22:00"
                                }

/usercommands:
    get:
        is: [ basic, secured, timeSearchable, limitedSearchable ]
        description: Get all user commands.
        responses:
            200:
                body:
                    application/json:
                        schema: userCommands
                        example: |
                            [
                                {
                                    "id": 1,
                                    "type": "UserConfiguration",
                                    "command": "Create",
                                    "targetName": "userConfiguration",
                                    "value": "ph_target:2:su:6",
                                    "timestamp": "2015-03-03 14:22:00",
                                    "done":1
                                },
                                {
                                    "id": 2,
                                    "type": "Actuators",
                                    "command": "Set",
                                    "targetName": "light",
                                    "value": "1",
                                    "timestamp": "2015-03-03 15:00:00",
                                    "done":1
                                },
                                {
                                    "id": 3,
                                    "type": "Actuators",
                                    "command": "Set",
                                    "targetName": "light",
                                    "value": "0",
                                    "timestamp": "2015-03-03 16:45:00",
                                    "done":0
                                }	
                            ]
    post:
        is: [ basic, secured ]
        description: Add a user command executate later by the python process
        queryParameters:
            command:
                description: Command name in enum "Create, Delete, Update, Set"
                example: "Create"
                required: true
                type: string
            targetName:
                description: Target to apply value
                example: "light"
                required: true
                type: string
            value:
                description: Value to apply
                example: "on"
                required: true
                type: string
        responses:
            201:
                body:
                    application/json:
                        schema: message
                        example: |
                            {
                                "code": 201,
                                "message": "Data created"
                            }
            400:
                body:
                    application/json:
                        schema: message
                        example: |
                            {
                                "code": 400,
                                "message": "Bad parameters"
                            }                            

    /{commandId}:
        description: Get information for a specific command.
        get:
            is: [ basic, secured, timeSearchable, limitedSearchable ]
            description: Get the command with `id = {commandId}`.
            responses:
                200:
                    body:
                        application/json:
                            schema: measures
                            example: |
                                {
                                    "id": 3,
                                    "type": "Actuators",
                                    "command": "Set",
                                    "targetName": "light",
                                    "value": "0",
                                    "timestamp": "2015-03-03 16:45:00",
                                    "done":0
                                }

/hardwareconfiguration:
    get:
        is: [ basic, secured ]
        description: Get all hardwares informations.
        responses:
            200:
                body:
                    application/json:
                        schema: hardwareConfiguration
                        example: |
                            [
                                {
                                    "id": 1 
                                    "name": "Pool Temperature Sensor"
                                    "pin": 1
                                    "type": "Analog"
                                    "IO": "Input"
                                    "PullUpDownResistor": "Up"
                                    "unit": "°C"
                                    "tension": "Null"
                                },
                                {
                                    "id": 2
                                    "name": "Pool Light"
                                    "pin": 5
                                    "type": "Numeric"
                                    "IO": "Output"
                                    "PullUpDownResistor": "None"
                                    "unit": "Null"
                                    "tension": "5"
                                }
                            ]
    /{hardwareId}:
        description: Get measure for a specific sensor.
        get:
            is: [ basic, secured ]
            description: Get the hardware information with `id = {hardwareId}`.
            responses:
                200:
                    body:
                        application/json:
                            schema: hardwareConfiguration
                            example: |
                                {
                                    "id": 1 
                                    "name": "Pool Temperature Sensor"
                                    "pin": 1
                                    "type": "Analog"
                                    "IO": "Input"
                                    "PullUpDownResistor": "Up"
                                    "unit": "°C"
                                    "tension": "Null"
                                }